from setuptools import setup, find_packages

setup(
    name='rqa',
    version='0.0',
    packages=find_packages(),
    description='RQA tutorial and analysis tools',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    author='Keri Heuer',
    author_email='keri.heuer@drexel.edu',
    license="MIT",
    url='https://github.com/keriheuer/rqa',
    install_requires=[
        'numpy',
        'matplotlib',
        "scipy==1.11.2",
        "ipywidgets", 
        "pillow", 
        "wheel", 
        "traitlets",
        "setuptools>=65",
        "Cython>=3.0.0",
        "seaborn",
        "pandas",
        "ipympl",
       # "warnings",
       # "mpl_toolkits",
        "ipyevents",
        "pyunicorn @ git+https://github.com/keriheuer/pyunicorn.git",
        # "pyunicorn @ git+https://github.com/pik-copan/pyunicorn.git#egg=pyunicorn"
    ],
    setup_requires=[
        'numpy',
        'matplotlib',
        "scipy==1.11.2",
        "ipywidgets", 
        "pillow", 
        "wheel", 
        "traitlets",
        "setuptools>=65",
        "Cython>=3.0.0",
        "seaborn",
        "pandas",
       # "warnings",
       # "mpl_toolkits",
        "ipyevents",
        "ipympl",
        "pyunicorn @ git+https://github.com/keriheuer/pyunicorn.git",
        # "pyunicorn @ git+https://github.com/pik-copan/pyunicorn.git#egg=pyunicorn"
    ],
    python_requires='>=3.8',
    package_data={
        'rqa': ['data/*'],
    },
)
